# example config.
# edit to your own preference.
links:
  -
    name: 'Home'
    href: '/'
  -
    name: 'About'
    href: '/about/'
  -
    name: 'example.com'
    href: 'https://example.com'
    # open this in a new tab
    external: true

notes:
  -
    content: 'Theme by subway.'
    href: 'https://github.com/cly767/subway'
    external: true
  -
    content: 'Add whatever you like here.'
    href: 'https://example.com'
    external: true
